[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
gift_aura = "BtYdTY7KuPGVNDvCvPB9UCc5EaurRrUQ4jGW2qqpmVff"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/hoando/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
